//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace NowPlayingForSpotify.Properties {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("NowPlayingForSpotify.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   厳密に型指定されたこのリソース クラスを使用して、すべての検索リソースに対し、
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Are you want to re-authentication? に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string AreYouWantToReAuthentication {
            get {
                return ResourceManager.GetString("AreYouWantToReAuthentication", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Can&apos;t connect to Spotify. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string CantConnectToSpotify {
            get {
                return ResourceManager.GetString("CantConnectToSpotify", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Are you sure you want to change back to the default format? に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ChangeToDefaultFormat {
            get {
                return ResourceManager.GetString("ChangeToDefaultFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Are you sure you want to exit without applying your changes? に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ExitWithoutApply {
            get {
                return ResourceManager.GetString("ExitWithoutApply", resourceCulture);
            }
        }
        
        /// <summary>
        ///   (アイコン) に類似した型 System.Drawing.Icon のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Icon NowPlayingForSpotifyIco {
            get {
                object obj = ResourceManager.GetObject("NowPlayingForSpotifyIco", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Bitmap NowPlayingForSpotifyPng {
            get {
                object obj = ResourceManager.GetObject("NowPlayingForSpotifyPng", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Please try again later. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string PleaseTryAgainLater {
            get {
                return ResourceManager.GetString("PleaseTryAgainLater", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Spotify does not running. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SpotifyDoesNotRunning {
            get {
                return ResourceManager.GetString("SpotifyDoesNotRunning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   SpotifyWebHelper does not running. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SpotifyWebHelperDoesNotRunning {
            get {
                return ResourceManager.GetString("SpotifyWebHelperDoesNotRunning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   There is no Twitter account. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ThereIsNotTwitterAccount {
            get {
                return ResourceManager.GetString("ThereIsNotTwitterAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   When you select Yes, the application will exit. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string WhenYouSelectYesProgramWillExit {
            get {
                return ResourceManager.GetString("WhenYouSelectYesProgramWillExit", resourceCulture);
            }
        }
    }
}
